try{
console.log(name);
const name = 'Matheus';
}catch(err){
    console.log('Erro: ', err);
}
console.log('Keep going...');